baseurl = "/"
title = "Still the Data"
author = "Conor Neilson"
copyright = "&copy; 2020"
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Conor Neilson"
introDescription = "Recovering Marine Biologist turned Data Scientist/Consultant."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
instagram = "condwanaland"
linkedin = "conor-neilson-49a04a141"
twitter = "condwanaland"
github = "condwanaland"

